all:
  hosts:
    proxmox:
      ansible_host: <PROXMOX_IP>
      ansible_user: root
    muspelheim:
      ansible_host: <MUSPELHEIM_IP>
      ansible_user: ubuntu
      ansible_ssh_common_args: '-J root@<JUMP_HOST_IP>'
    midgard:
      ansible_host: <MIDGARD_IP>
      ansible_user: ubuntu
      ansible_ssh_common_args: '-J root@<JUMP_HOST_IP>'
    nidavellir:
      ansible_host: <NIDAVELLIR_IP>
      ansible_user: root
      ansible_ssh_common_args: '-J root@<JUMP_HOST_IP>'
